### ISSUE TITLE
Customize configuration using custom properties file

### ISSUE THREAD

**Issue by iromli** [GluuFederation/message-consumer#2]
As far as I know message-consumer reads the config from `application-prod-xxx.properties` file, and to change them without re-building the jar file, I can pass options like `--spring.activemq.broker-url=xxx` or `spring.datasource.password=xxx` (which I want to avoid passing sensitive data via command line).

Is it possible to load custom configuration, e.g. from `/path/to/any.properties` to override value in default `application-prod-xxx.properties`?

**Comment by worm333** [comment]
In order to override embedded message-consumer configuration, you can add the following arguments in console:

* `--spring.config.location=file:${full_path_to_config_should_end_with_/} `
*  `--spring.config.name=${customized-application-configuration-without-.properties}`


Here is an example how you can run the app and override default configuration with `/home/configurations/application-prod-mysql.properties`:
```
java -jar target/message-consumer-0.0.1-SNAPSHOT.jar --spring.config.location=file:/home/configurations/ --spring.config.name=application-prod-mysql
```
Note. In this case there is no need to specify `--spring.profiles.active` property

**Comment by iromli** [comment]
Worked like a charm. Thanks.
